# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core API to Azure Web App - Cactus

on:
  push:
    branches:
      - 192-crear-rama-para-los-pipelines
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    permissions:
      contents: read #Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build ONLY the API project
        run: dotnet build src/AppForSEII2526.API/AppForSEII2526.API.csproj --configuration Release

      - name: Publish ONLY the API project
        run: dotnet publish src/AppForSEII2526.API/AppForSEII2526.API.csproj --configuration Release --output "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #Required for requesting the JWT
      contents: read  #Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7BA686E968954410A145D48E424A7053 }}
          tenant-id: ${{ secrets.AZUREAPPservice_TENANTID_308CE381D141451E969689F2DBCC50F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CC42D5A92CDF495E9531F049746A262B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Cactus'
          slot-name: 'Production'
          package: .


          
